[package]
name = "rust_synth"
version = "0.1.0"
authors = ["Masashi Yoshikawa <earnest.marshi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hound = "3.5.1"
